on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0.0, v20.15.10

name: Create Release

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: biliplus.zip
          body: |
            Please refer to [CHANGELOG.md](https://github.com/0xlau/biliplus/blob/main/CHANGELOG.md) for details.
